MVC/Models/MainView.cs
using PagedList;
using Service.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Xml.Linq;

namespace MVC.Models
{
    
    public class MainView
    {
        public IEnumerable<VehicleMake> MakerEnumerable;
        
        public int selectedMaker { get; set; }

        public IEnumerable<SelectListItem> ListMakers
        {
            get { return new SelectList(MakerEnumerable, "Id", "Name"); }
        }
        public IPagedList<VehicleMakeView> MakePaged { get; set; }
        public IPagedList<VehicleModelView> ModelPaged { get; set; }
    }
}

MVC/Models/VehicleMakeView.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models
{
    public class VehicleMakeView  
    { 
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Please enter Make Name.")]
        [StringLength(50, ErrorMessage = "The Make Name must be less than {1} characters.")]
        public string Name { get; set; }
        public string Abrv { get; set; }
    }
}

MVC/Models/VehicleModelMakerView.cs
using PagedList;
using Service.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class VehicleModelMakerView
    {
        public string SortOrder { get; set; }
        public string CurrentFilter { get; set; }
        public string SearchValue { get; set; }
        public int? Page { get; set; } = 1;
        public int ResultsPerPage { get; set; } = 5;
        public IPagedList<VehicleModelView> Models { get; set; }
        public IEnumerable<VehicleMake> AllMakes { get; set;  }
    }
}

MVC/Models/VehicleModelView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models
{
    
    public class VehicleModelView
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Please enter Model Name.")]
        [StringLength(50, ErrorMessage = "The Model Name must be less than {1} characters.")]
        public string Name { get; set; }
        public string Abrv { get; set; }
        public Guid VehicleMakeId { get; set; }
        public IEnumerable<VehicleMakeView> MakeEnumerable { get; set; }
        public VehicleMakeView Make { get; set; }
    }
}

MVC/Controllers/ModelController.cs
using System.Net;
using System.Web.Mvc;
using System;
using PagedList;
using MVC.Models;
using System.Collections.Generic;
using AutoMapper;
using Service.Common.Services;
using Model.Common;
using System.Threading.Tasks;
using Common;
using System.Collections;

namespace MVC_Project.Controllers
{
    public class ModelController : Controller
    {
        private IVehicleModelService service;

        public ModelController(IVehicleModelService service)
        {
            this.service = service;
        }

        // GET: Models
        public async Task<ActionResult> Index(bool sortOrder, string currentFilter, string searchString, int? page, int? resultsPerPage)
        {
            SystemDataModel systemDataModel = new SystemDataModel();

            ViewBag.ResultsPerPage = resultsPerPage;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm =  !sortOrder;

            systemDataModel.SearchValue = searchString;
            systemDataModel.CurrentFilter = currentFilter;
            systemDataModel.SortOrder = sortOrder;
            systemDataModel.ResultsPerPage = (resultsPerPage ?? 5);
            systemDataModel.Page = (page ?? 1);

            StaticPagedList<IVehicleModelModel> items = await service.GetVehicleDataPagedAsync(systemDataModel);
            StaticPagedList<VehicleModelView> modelViewPaged = Mapper.Map<StaticPagedList<IVehicleModelModel>, StaticPagedList<VehicleModelView>>(items);
            ViewBag.CurrentFilter = systemDataModel.SearchValue;

            return View(modelViewPaged);
        }

        // GET: Models/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            IVehicleModelModel model = await service.ReadAsync(id);
            VehicleModelView modelView = Mapper.Map<VehicleModelView>(model);

            if (modelView == null)
            {
                return HttpNotFound();
            }
            return View(modelView);
        }

        // GET: Models/Create
        public async Task<ActionResult> Create()
        {
            VehicleModelView vehicleModelView = new VehicleModelView
            {
                MakeEnumerable = Mapper.Map<IEnumerable<IVehicleMakeModel>, IEnumerable<VehicleMakeView>>(await service.GetAllMakeAsync())
            };
            return View(vehicleModelView);
        }

        // POST: Models/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id, Make ,VehicleMakeId, Make.Id, MakeID,Name,Abrv")] VehicleModelView modelView)
        {

            IVehicleModelModel model = Mapper.Map<IVehicleModelModel>(modelView);
            if (ModelState.IsValid)
            {
                await service.CreateAsync(model);
                return RedirectToAction("Index");
            }
            modelView = Mapper.Map<VehicleModelView>(model);
            return View(modelView);

        }

        // GET: Models/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            VehicleModelView modelView = Mapper.Map<VehicleModelView>(await service.ReadAsync(id));
            if (modelView == null)
            {
                return HttpNotFound();
            }
            //IEnumerable<VehicleMakeView> modelViewList = Mapper.Map<IEnumerable<VehicleModelView>(service.GetMakesAsync());

            //ViewBag.MakerList = new SelectList(), "Id", "Name");
            return View(modelView);
        }

        // POST: Models/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,VehicleMakeId,Name,Abrv")] VehicleModelView modelView)
        {
            IVehicleModelModel model = Mapper.Map<IVehicleModelModel>(modelView);

            if (ModelState.IsValid)
            {
                await service.UpdateAsync(model);

                return RedirectToAction("Index");
            }
            //VehicleModelView modelView = Mapper.Map<VehicleModelView>(model);
            return View(modelView);
        }

        // GET: Models/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IVehicleModelModel model = await service.ReadAsync(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            VehicleModelView modelView = Mapper.Map<VehicleModelView>(model);
            return View(modelView);
        }

        // POST: Models/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid? id)
        {
            IVehicleModelModel model = await service.ReadAsync(id);
            await service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

MVC/Views/Model/Create.cshtml
@model  MVC.Models.VehicleModelView

@{
    ViewBag.Title = "Create";
}

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="panel panel-success" align="center">
    <div class="panel-heading">
        <h2>Create new Make</h2>
    </div>

    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(x => x.Make.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.VehicleMakeId, new SelectList(Model.MakeEnumerable, "Id", "Name"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleMakeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>


        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

    </div>
</div>
}

MVC/Views/Model/Delete.cshtml
@model MVC.Models.VehicleModelView

@{
    ViewBag.Title = "Delete";
}

<br>
<div class="panel panel-danger">
    @* PANEL-HEADING *@
    <div class="panel-heading">

        <h2>Delete this item?</h2>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="panel-body" align="center">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Id)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Id)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Make.Id)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Make.Id)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Abrv)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Abrv)
                </dd>

            </dl>


            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index", null, new{@class="btn btn-default" })
            </div>

        </div>
    }

MVC/Views/Model/Details.cshtml
@model MVC.Models.VehicleModelView

@{
    ViewBag.Title = "Details";
}
<br />

<div class="panel panel-info" align="center">
    <div class="panel-heading">
        <h2>Details</h2>
    </div>

    <div class="panel-body">
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>

            <dt>
                Id (Make)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Make.Id)
            </dd>

            <dt>
                Name (Make)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Make.Name)
            </dd>

            <dt>
                Name (Model)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Abrv)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Abrv)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class="btn btn-warning"}) |
        @Html.ActionLink("Back to List", "Index", null, new { @class="btn btn-default"})
    </p>
</div>

MVC/Views/Model/Edit.cshtml
@model MVC.Models.VehicleModelView
@{
    ViewBag.Title = "Edit";
}

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="panel panel-warning">
            <div class="panel-heading"><h2>Edit this item?</h2></div>

            <div class="panel-body" align="center">

                <div class="form-horizontal">
                         <div class="form-group">
                        @Html.LabelFor(model => model.Id, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("VehicleMakeId", ViewBag.MakerList as SelectList)
                            @Html.ValidationMessageFor(model => model.Make.Id)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Abrv, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Abrv, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Abrv, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-success" />
                            @Html.ActionLink("Back to List", "Index", null, new { @class="btn btn-default"})
                        </div>
                    </div>
                </div>


                <div>
                    
                </div>
                </div>
            </div>
                }
                

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

MVC/Views/Model/Index.cshtml
@model PagedList.IPagedList<MVC.Models.VehicleModelView>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@using MVC;

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Model", FormMethod.Get))
{

    @Html.ActionLink("Create Model", "Create", null, new { @class = "btn btn-success" })
    <br>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
                <div class="input-group">
                    <span class="input-group-btn">
                        <div style="width: 60%; float:left" align="left">
                            Search: @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "search model or make..." })
                            <button class="btn btn-default" type="submit">Go!</button>
                        </div>

                        <div style="width: 40%; float:right" align="right">
                            Show @Html.DropDownList("resultsPerPage", Enumerable.Range(1, 10).Select(i => new SelectListItem { Text = (i * 5).ToString(), Value = (i * 5).ToString() }), new { onchange = "this.form.submit();", @class = "btn btn-default dropdown-toggle" }) Per Page
                        </div>
                    </span>
                </div>
        </div>


        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>
                        Make Name
                    </th>
                    <th>
                        @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter, resultsPerPage = ViewBag.ResultsPerPage })
                    </th>
                    <th>
                        Abrv
                    </th>
                    <th>
                    </th>
                    <th>
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Make.Name)
                        </td>
                        <td>
                            @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Abrv)
                        </td>
                        <td>
                            <div align="right">
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
                            </div>

                        </td>
                    </tr>
                }
            </table>
        </div>

        <div class="panel-footer">
                @Html.PagedListPager(Model, page => Url.Action("Index", "Model", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, resultsPerPage = ViewBag.ResultsPerPage }))

        </div>
    </div>
}