MVC/Controllers/MakeController.cs
using System;
using System.Web.Mvc;
using System.Net;
using MVC.Models;
using PagedList;
using AutoMapper;
using System.Linq;
using Service.Common.Services;
using Model.Common;
using System.Threading.Tasks;
using Common;

namespace MVC.Controllers
{
    public class MakeController : Controller
    {      
        private readonly IVehicleMakeService service;

        public MakeController(IVehicleMakeService vehicleMakeService)
        {
            service = vehicleMakeService;
        }

        // GET: /Make/
        //[Route("Index")]
        public async Task<ViewResult> Index(bool sortOrder, string currentFilter, string searchString, int? page, int? resultsPerPage)
        {
            AsyncManager.OutstandingOperations.Increment();

            SystemDataModel systemDataModel = new SystemDataModel();

            ViewBag.ResultsPerPage = resultsPerPage;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = !sortOrder;

            systemDataModel.SearchValue = searchString;
            systemDataModel.CurrentFilter = currentFilter;
            systemDataModel.SortOrder = sortOrder;
            systemDataModel.ResultsPerPage = (resultsPerPage ?? 5);
            systemDataModel.Page = (page ?? 1);


            StaticPagedList<IVehicleMakeModel> makeItems = await service.GetVehicleDataPagedAsync(systemDataModel);
            StaticPagedList<VehicleMakeView> makeViewItems = Mapper.Map<StaticPagedList<IVehicleMakeModel>, StaticPagedList<VehicleMakeView>>(makeItems);
                
           ViewBag.CurrentFilter = systemDataModel.SearchValue;
            return View(makeViewItems);
        }

        // GET: /Make/Details/5]
        [Route("Details")]
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IVehicleMakeModel make = await service.ReadAsync(id);
            VehicleMakeView makeView = Mapper.Map<VehicleMakeView>(make);
            
            if (makeView == null)
            {
                return HttpNotFound();
            }
            return View(makeView);
        }

        // GET: /Make/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Make/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Abrv")] VehicleMakeView makeView)
        {
            IVehicleMakeModel make = Mapper.Map<IVehicleMakeModel>(makeView);

            if (ModelState.IsValid)
            {
                await service.CreateAsync(make);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.error = "Something went wrong";
                var errors = ModelState.Values.SelectMany(x => x.Errors);
                return View(makeView);

            }
        }


        // GET: /Make/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IVehicleMakeModel make = await service.ReadAsync(id);
            if (make == null)
            {
                return HttpNotFound();
            }
            VehicleMakeView makeView = Mapper.Map<VehicleMakeView>(make);
            return View(makeView);
        }

        // POST: /Make/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Abrv")] VehicleMakeView makeView)
        {
            IVehicleMakeModel make = Mapper.Map<IVehicleMakeModel>(makeView);

            if (ModelState.IsValid)
            {
                await service.UpdateAsync(make);
                return RedirectToAction("Index");
            }

            
            return View(makeView);
        }

        // GET: /Make/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IVehicleMakeModel make = await service.ReadAsync(id);
            VehicleMakeView makeView = Mapper.Map<VehicleMakeView>(make);
            if (makeView == null)
            {
                return HttpNotFound();
            }
           
            return View(makeView);
        }

        // POST: /Make/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmedAsync(Guid? id)
        {
            IVehicleMakeModel maker = await service.ReadAsync(id);
            await service.DeleteAsync(id);
            return RedirectToAction("Index");
        }

  
    }
}

MVC/Views/Make/Create.cshtml
@model MVC.Models.VehicleMakeView

@{
    ViewBag.Title = "Create";
}

@if(!String.IsNullOrWhiteSpace(ViewBag.Message)){
<div class="alert alert-danger" role="alert">
    <a href="#" class="alert-link">@ViewBag.error</a>
</div>
 }
<br />

<div class="panel panel-success">
    <div class="panel-heading">
        <h2>Create new Make</h2>
    </div>

    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal" align="center">
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10" align="left">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Abrv, new { @class = "control-label col-md-2" })
                    <div class="col-md-10" align="left">
                        @Html.EditorFor(model => model.Abrv)
                        @Html.ValidationMessageFor(model => model.Abrv)
                    </div>
                </div>

                <br />
                <br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
        }

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Views/Make/Delete.cshtml
@model MVC.Models.VehicleMakeView
@{
    ViewBag.Title = "Delete";
}

<br>
<div class="panel panel-danger">
    @* PANEL-HEADING *@
    <div class="panel-heading">

        <h2>Delete this item?</h2>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="panel-body">
            <dl class="dl-horizontal" align="center">
                <dt>
                    @Html.DisplayNameFor(model => model.Id)
                </dt>

                <dd align="left">
                    @Html.DisplayFor(model => model.Id)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd align="left">
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Abrv)
                </dt>

                <dd align="left">
                    @Html.DisplayFor(model => model.Abrv)
                </dd>

            </dl>


            <div align="center">
                <input type="submit" value="Delete" class="btn btn-danger" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>

        </div>
}

MVC/Views/Make/Details.cshtml
@model MVC.Models.VehicleMakeView

@{
    ViewBag.Title = "Details";
}

<br />

<div class="panel panel-info">
    <div class="panel-heading">
        <h2>Details for '@Model.Name'</h2>
    </div>
    <div class="panel-body" >

        <div align ="center">
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Id)
                </dt>

                <dd align="left">
                    @Html.DisplayFor(model => model.Id)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd align="left">
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Abrv)
                </dt>

                <dd align="left">
                    @Html.DisplayFor(model => model.Abrv)
                </dd>

            </dl>
        </div>
        <div align="center">
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>

MVC/Views/Make/Edit.cshtml
@model MVC.Models.VehicleMakeView

@{
    ViewBag.Title = "Edit";
}
<br>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="panel panel-warning">
    <div class="panel-heading"><h2>Edit this item?</h2></div>
    
    <div class="panel-body" align ="center">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-lg-10" align="left">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group" >
            @Html.LabelFor(model => model.Abrv, new { @class = "control-label col-md-2" })
            <div class="col-md-10" align="left">
                @Html.EditorFor(model => model.Abrv)
                @Html.ValidationMessageFor(model => model.Abrv)
            </div>
        </div>

        <br />
        <br />
        <div class="form-group">
            <div align ="center">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>


}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Views/Make/Index.cshtml
@model PagedList.IPagedList<MVC.Models.VehicleMakeView>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Make", FormMethod.Get))
{
    <p>
        @Html.ActionLink("Create Make", "Create", null, new { @class = "btn btn-success" })
    </p>

    <div class="panel panel-default">

        <div class="panel-heading">
                <div class="input-group">
                    <span class="input-group-btn">
                        <div style="width: 60%; float:left" align="left">
                            Search: @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "search model or make..." })
                            <button class="btn btn-default" type="submit">Go!</button>
                        </div>

                        <div style="width: 40%; float:right" align="right">
                            Show @Html.DropDownList("resultsPerPage", Enumerable.Range(1, 10).Select(i => new SelectListItem { Text = (i * 5).ToString(), Value = (i * 5).ToString() }), new { onchange = "this.form.submit();", @class = "btn btn-default dropdown-toggle" }) Per Page
                        </div>
                    </span>
            </div>

        </div>
        <table class="table">
            <tr>
                <th>
                    @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter, resultsPerPage = ViewBag.ResultsPerPage })
                </th>
                <th>
                    Abrv
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Abrv)
                    </td>
                    <td>
                        <div align="right">
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
                        </div>
                    </td>
                </tr>
            }
            
        </table>
 
    <div class="panel-footer">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, resultsPerPage = ViewBag.ResultsPerPage }))
    </div>
    </div>
}